#!/bin/bash
pok_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

mkdir pokemon_data


#for pok in "${pok_list[@]}"
#do
#	echo "Fetching data for $pok...;"
#	touch pokemon_data/"$pok".json;
#	API_URL="https://pokeapi.co/api/v2/pokemon/$pok/"
#	(curl -s -w "%{http_code}" -o pokemon_data/"$pok".json "$API_URL" --header 'Content-Type: application/json' && echo Saved data to pokemon_data/"$pok".json) &
#done
#
#wait

(trap 'kill 0' SIGINT;
parallel --jobs 5 curl -s -w "%{http_code}" -o pokemon_data/"{}".json "https://pokeapi.co/api/v2/pokemon/{}/" --header "Content-Type: application/json" ::: "${pok_list[@]}")
wait
